@startuml
class AppConsts {
+ {static} URL LOG4J_PROPERTIES
+ {static} String SYSTEM_PROPERTY
~ {static} String APP_TITLE
+ {static} int BOARD_MARGIN_TOP
~ {static} int BOARD_WIDTH
~ {static} int BOARD_HEIGHT
~ {static} double GAME_SPEED
~ {static} Image ICON_16
~ {static} Image ICON_32
~ {static} Image ICON_64
~ {static} Image ICON_128
~ {static} int LEVELS
~ {static} int TICKSxFRAME
~ {static} Image ENEMYSHIP_SPRITE_IMAGE_1
~ {static} Image ENEMYSHIP_SPRITE_IMAGE_2
~ {static} Image ENEMYSHIP_SPRITE_IMAGE_3
~ {static} Image ENEMYBARRIER4_SPRITE_IMAGE
~ {static} Image ENEMYTOWER3_SPRITE_IMAGE
~ {static} int INIT_LEVEL
~ {static} int INIT_LIFES
~ {static} int PTS_ENEMYSHIP
~ {static} int PTS_NEWLEVEL
~ {static} Image SHIP_SPRITE_IMAGE
~ {static} Image LIFES_SPRITE_IMAGE
~ {static} Image LASER_SPRITE_IMAGE
~ {static} Image EXPLOSION_9_SPRITE_IMAGE
~ {static} Image EXPLOSION_12_SPRITE_IMAGE
~ {static} double MARGIN_LEFT
~ {static} double MARGIN_TOP
~ {static} String TXT_YOU_CAN
~ {static} String TXT_PRESS_ENTER
~ {static} String TXT_TO_START
~ {static} String TXT_TO_CONTINUE
~ {static} String TXT_YOU_WON
~ {static} String TXT_YOU_LOST
~ {static} String TXT_LEVEL
~ {static} String TXT_POINTS
~ {static} Image COVER_IMAGE
~ {static} Font FONT_HELVETICA_16
~ {static} Font FONT_HELVETICA_52
+ {static} Image BALL_SPRITE_IMAGE
+ {static} int SHIP_ROWS
+ {static} int SHIP_COLS
+ {static} int SHIP_UP
+ {static} int SHIP_DOWN
+ {static} int SHIP_RIGHT
+ {static} int SHIP_LEFT
+ {static} int SHIP_MAX_SPEED
+ {static} int ENEMYSHIP_ROWS
+ {static} int ENEMYSHIP_COLS
+ {static} int ENEMYSHIP_MAX_SPEED
+ {static} double ENEMYSHIP_ALFA
+ {static} int ENEMYBARRIER_ROWS
+ {static} int ENEMYBARRIER_COLS
+ {static} int ENEMYTOWER_ROWS
+ {static} int ENEMYTOWER_COLS
+ {static} double ENEMYMONSTER_ALFA
+ {static} int LIFES_ROWS
+ {static} int LIFES_COLS
+ {static} double LIFES_ALFA
- <<Create>> AppConsts()
}
@enduml