@startuml
abstract class ASprite {
# int rows
# int cols
# int x
# int y
# int xSpeed
# int ySpeed
# Image img
# int currentFrame
# int width
# int height
# int side
+ <<Create>> ASprite(Image,int,int)
+ void setPos(int,int)
+ int getXSpeed()
+ void setXSpeed(int)
+ int getYSpeed()
+ void setYSpeed(int)
+ Rect getRect()
+ Rect[] getRects()
+ boolean collides(ASprite)
+ void draw(GraphicsContext)
+ {abstract}void update()
}
@enduml